### Create new post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My Second Post",
    "content": "This is the content of my second post.",
    "owner": "64fe4c2ae7891b6cf7890def"
}

### Get all posts
GET http://localhost:3000/posts

### Get post by ID
GET http://localhost:3000/posts/676983c5ac27c9ccac30b6b6

### Update post data
PUT http://localhost:3000/posts/675011fbf37579481a85cf0e
Content-Type: application/json

{
    "title": "My LASTTTTTTTTT Post",
    "owner": "64fe4c2ae7891b6cf7890def"
}

### Get Posts by Owner
GET http://localhost:3000/posts?owner=64fe4c2ae7891b6cf7890def

### Delete a Post by ID
DELETE http://localhost:3000/posts/673b778744cf4e7b4ffd1bb5
Content-Type: application/json

### Create new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "commenter": "Yuval",
    "postID": "673b7041241ed1b7a603a64b",
    "content": "This is the best post ever!"
}

### Get all comments
GET http://localhost:3000/comments

### Get comment by Post ID
GET http://localhost:3000/comments/comment/677c56995ce8a6387db111a7

### Update comment data
PUT http://localhost:3000/comments/675012e5f37579481a85cf15
Content-Type: application/json

{
    "postID": "12345"
}

### Delete a Comment by ID
DELETE http://localhost:3000/comments/675012e5f37579481a85cf15
Content-Type: application/json

### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Yuval",
    "username": "yuval123",
    "email": "yuval12@example.com",
    "password": "yuval123"
}

### Get all users
GET http://localhost:3000/users

### Get user by ID
GET http://localhost:3000/users/675568e6d4e30f4f7b60baff

### Update user data
PUT http://localhost:3000/users/675568e6d4e30f4f7b60baff
Content-Type: application/json

{
    "email": "2@example.com"
}

### Delete a user by ID
DELETE http://localhost:3000/users/675568e6d4e30f4f7b60baff
Content-Type: application/json

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "test123"
}

### Check registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "securepassword",
    "username": "newuser123"
}

### Login with new user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "securepassword"
}

### Regiter weak 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "weakpassword@example.com",
    "password": "123",
    "username": "weakuser"
}

### Send a question to chatGPT
POST http://localhost:3000/chat
Content-Type: application/json

{
    "question": "What dog breed has a lot of energy?"
}

### Send a refresh-token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzU3MTUyMWUzNTU5N2E3OTQ5NjViMjQiLCJpYXQiOjE3Mzc2NDczNzEsImV4cCI6MTczODI1MjE3MX0._kzP4fvzZ_IfEzSUVPXd5JL4PmeIBqxMWXO-8GR8UJQ"
}

### Like a post
GET http://localhost:3000/likes/6751d078131e9d95af40678c/679760c511da5bbc411985e7
